### ISSUE TITLE
trouble getting license 

### ISSUE THREAD

**Issue by reisdefreitasm** [okviz/calendar-pro-issues#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i'm trying to get the calendar pro license with no success...I constantly get stuck after choosing a plan... does anyone have a clue about what's happening?

btw i'm typing from brazil.

thanks yall

### Power BI

Power BI service

### Power BI Version

visual license calendar pro

### Sample report

https://appsource.microsoft.com/en-us/marketplace/checkout/okvizcorp1634637213047.calendarprobyokviz?tab=Overview

### Screenshot

![image](https://user-images.githubusercontent.com/112182718/186918275-62e21783-734f-4178-ac28-70fa72444143.png)

**Comment by danieleperilli** [comment]
The license is purchased through Microsoft website, we don't have any control over the checkout process on the AppSource. Please open a ticket with Microsoft.
