### ISSUE TITLE
Thousand separator . in es-ES localization 

### ISSUE THREAD

**Issue by ErnestoMeso** [okviz/calendar-pro-issues#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Thousand separator **.** and decimal **,** in **es-ES** localization doesn't work.

Example: 
Localization **en-US** 37,000.55
Localization **es-ES** _37,000.55 incorrect_ => **37.000,55** correct

### Power BI

Power BI service

### Sample report

[calendar-bug.zip](https://github.com/okviz/calendar-pro-issues/files/13987836/calendar-bug.zip)

### Screenshot

Configured localization in PBI Desktop **es-ES**:
![image](https://github.com/okviz/calendar-pro-issues/assets/157111899/b45c977a-550f-4be7-b0e4-0b856f344063)

In PBI Service, work month localization, but doesn't work thousands numeric separator and decimal delimiter:
![image](https://github.com/okviz/calendar-pro-issues/assets/157111899/245fb3ee-53dd-49ce-8390-be0c38806921)

**Comment by danieleperilli** [comment]
There seems to be a bug in the Power BI library that we use under the hood. I have informed the Microsoft team and will update this issue when we have updates.

**Comment by danieleperilli** [comment]
I have some updates: a recent change in the Power BI library that we use to format numbers has excluded custom locales. This means we have to make up a different way to allow users to provide custom locales for number formatting, and that takes time. In the meantime, the solution is to set Power Bi language to the preferred language-that way, numbers and dates will be formatted the correct way.

**Comment by danieleperilli** [comment]
We introduced a specific option to control the separators in v1.0.5.4
