### ISSUE TITLE
The option Cell Appearance > Data color doesn't work properly

### ISSUE THREAD

**Issue by federico-trotta** [okviz/calendar-pro-issues#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The cells that contain data should be colored according to the **Data color** option, but this does not work. Regarding the specific case, the cells should be colored in blue.

![bug-data-color_1](https://github.com/okviz/calendar-pro-issues/assets/87845182/3e2b6d7e-e6f5-4be2-bf14-fa6148988631)
![bug-data-color_2](https://github.com/okviz/calendar-pro-issues/assets/87845182/9c1e962f-e3eb-4d23-9c32-5134e90ee405)

> **NOTE**: The advanced rule color was disabled.

### Power BI

Power BI Desktop

### Steps To Reproduce

**STEP 1**: Disable any advanced color rule in the **Advanced editor**.
**STEP 2**: Go to the option **Cell Appearance** and choose a color in the option **Data color**.

The cells that contain data will be blank instead of being colored by the color you have chosen.

### Sample report

[report_to_test_bug_data_color.zip](https://github.com/okviz/calendar-pro-issues/files/15290885/report_to_test_bug_data_color.zip)

**Comment by danieleperilli** [comment]
Fixed in v1.0.5.5.
