### ISSUE TITLE
The Display unit option does not work properly

### ISSUE THREAD

**Issue by federico-trotta** [okviz/calendar-pro-issues#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The **Display unit** option in **Events/Holidays labels** should manage the visualization of events based on "big quantities", based on the conversion of the units, but currently it does nothing when we change the units.

### Power BI

Power BI Desktop

### Steps To Reproduce

**STEP 1**: Attach a measure that represent numbers in the **Event** role field.
**STEP 2**: Set **On** the **Events** toggle option.
**STEP 3**: Go to the **Events/Holidays labels** option.
**STEP 4**: Use the **Display unit** option and see that the numbers displayed don't change.

### Sample report

[report_to_test.zip](https://github.com/okviz/calendar-pro-issues/files/15298564/report_to_test.zip)

### Screenshot

![display_unit](https://github.com/okviz/calendar-pro-issues/assets/87845182/9fd0fafc-b326-4adc-81ba-ea1787d9ba27)

**Comment by danieleperilli** [comment]
Fixed in v1.0.5.5
