### ISSUE TITLE
The option **Alignment** in **Axis: Years** does not work 

### ISSUE THREAD

**Issue by federico-trotta** [okviz/calendar-pro-issues#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In **Axis: Years**, the option **Alignment** does not work. When you try to use it, the text does not move (it does not align on the left, center, or right).

### Power BI

Power BI Desktop

### Steps To Reproduce

**STEP 1**: In **Appearance**, select **Chart** in the **Display mode** option.
**STEP 2**: In **Axis: Years**, try the **Alignment** option and see the text does not move in the intended direction.

### Sample report

[test_alignment.zip](https://github.com/okviz/calendar-pro-issues/files/15390048/test_alignment.zip)

### Screenshot

![Alignment](https://github.com/okviz/calendar-pro-issues/assets/87845182/9f8cc9e4-d1ab-4268-83dc-4c60f1b1a676)

**Comment by danieleperilli** [comment]
Fixed in v1.0.5.5
