### ISSUE TITLE
Power BI não consegue adicionar Licença para desbloquear

### ISSUE THREAD

**Issue by JORGESENNA** [okviz/calendar-pro-issues#2]
### The feature request

![image](https://user-images.githubusercontent.com/39027687/191267864-6e2c9677-4eb2-4449-ad55-34ffb6918a2f.png)

### Proposed solution

![image](https://user-images.githubusercontent.com/39027687/191267894-522528c7-b0aa-40e1-8c69-7b615840b259.png)

**Comment by JORGESENNA** [comment]
não da para atribuir  ao usuario

**Comment by JORGESENNA** [comment]
![image](https://user-images.githubusercontent.com/39027687/191268218-2680b18c-3165-4030-9616-0fc7884ffe8a.png)

**Comment by marcosqlbi** [comment]
Check how to assign the licenses here: https://docs.okviz.com/calendar-pro/licensing

**Comment by JORGESENNA** [comment]
![image](https://user-images.githubusercontent.com/39027687/191268696-a94dff42-b504-46b5-a16b-e98a28f899df.png)

**Comment by JORGESENNA** [comment]
não tem onde add licença

**Comment by marcosqlbi** [comment]
You should check with Microsoft, which also has a FAQ page: https://learn.microsoft.com/en-us/power-bi/developer/visuals/licensing-faq
If you are still unable to figure out how to assign the license, you should contact Microsoft support for that: https://powerbi.microsoft.com/en-us/support/pro/

**Comment by danieleperilli** [comment]
Closed for inactivity.
