### ISSUE TITLE
Measure to be a

### ISSUE THREAD

**Issue by cwsbailey** [okviz/calendar-pro-issues#4]
### The feature request

Currently using weekly granularity evaluates the measure by day and then sums (or other chosen function) for the days in that week.

### Proposed solution

 Instead, the measure should be evaluated for the date period in question. 

The picture attached shows an example. 

On the left is the calendar daily granulatarity, showing week 26 with the measure evaluated for each day (values range from 223 to 263).

On the right is the calendar with weekly granularity showing week 26 with a value of 1.48k

As this measure is an average, the correct value when evaluated for all data in week 26 is 248.

This is different to changing the data aggregation to "average" as this is an average of averages.

![image](https://user-images.githubusercontent.com/18232308/195848697-ccd7b73d-2d1b-42af-9227-61a12eb40f75.png)

**Comment by marcosqlbi** [comment]
While completely reasonable, this requirement cannot be implemented in Calendar Pro at the moment.
Calendar Pro binds only the Date column, so any aggregation over the date hierarchy is made internally to the visual based on the data computed at the date level. With the current architecture of Power BI, the only way to compute a measure at different granularities (e.g. week) is by creating a date table that has the required granularity and use that column in the binding to a visual. 
If that would be possible, would you use Calendar Pro by binding other columns you have in the Date table that are not the Date column?

**Comment by cwsbailey** [comment]
Hi Marco,

Thanks for your response. I managed a way around this by making a weekly
average measure and then aggregating values by averaging instead of summing.

On a separate problem, I am wanting to publish my report to an app for
multiple people to see, ideally also on a public page. There is a licensing
issue when published publicly - Is there a license that I can buy that
allows me to publish the report publicly?

Thanks,

Charlie

**Comment by marcosqlbi** [comment]
We would like to offer the license for public pages as we already do for Smart Filter Pro (which has another license type and cannot be certified by Microsoft yet). Unfortunately, this is not possible yet. I asked Microsoft whether they have news about it, I'll keep you posted.
