### ISSUE TITLE
Not really a bug - looking for help

### ISSUE THREAD

**Issue by golec2github** [okviz/calendar-pro-issues#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using Calendar Pro to build out a calendar that counts how many staff members are out on a particular day. We use it to see which days we may be short on staff and struggle to get subs for (we are a school district). There are two thresholds, one for Monday-Thursday and one for Friday. Right now, I am using my Monday-Thursday threshold to color the cells. I would like to have a different value to color the cells for Fridays, as the warning levels are lower.

Thanks,

### Power BI

Power BI Desktop

### Sample report

![image](https://user-images.githubusercontent.com/49169279/200893610-fb0e48f5-ccb1-47d1-9f5f-02230c50941d.png)

### Screenshot

![image](https://user-images.githubusercontent.com/49169279/200893631-92bcd5c7-0dfc-4052-b53e-4cf6bb5cb1d9.png)

**Comment by danieleperilli** [comment]
It's not something exposed by the visual. Perhaps you can can achieve the desired result with a special measure and different color rules...
