### ISSUE TITLE
Default to Today

### ISSUE THREAD

**Issue by coshaner** [okviz/calendar-pro-issues#6]
### The feature request

It would be nice if there was a default date feature that would allow you to default the calendar to todays month.

### Proposed solution

Default date to today selector

**Comment by danieleperilli** [comment]
It is something we will add in the next update, scheduled for mid January. Please consider that this will not available in the AppSource before beginning of March.

**Comment by danieleperilli** [comment]
Here you are: https://github.com/okviz/calendar-pro-issues/releases/tag/v1.0.4.0
